valor = input("Digite algo: ")

print('--------------------------')
print('O tipo primitivo é? ', type(valor))
print('--------------------------')
print('Só tem espaço? ', valor.isspace())
print('--------------------------')
print('É um número? ', valor.isnumeric())
print('--------------------------')
print('É alfanumérico? ', valor.isalnum())
print('--------------------------')
print('Está em maiúscula? ', valor.isupper())
print('--------------------------')
print('Está em minúscula? ', valor.islower())
print('--------------------------')
print('Está capitalizada? ', valor.istitle())
print('--------------------------')
print('É alfabético? ', valor.isalpha())
